### PR TITLE
Removing theme-related media features

### PR DESCRIPTION
**Pull request by rachelandrew**
Part of https://github.com/mdn/content/issues/2515

Removing the theme-related content from the archive.

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
Ah, you beat me to it ;-)

This looks good. I actually don't think we need the redirects.

**Comment by peterbe** [comment]
We're not building archived content. Do we need to run a build now?
Also, we're not deleting anything from the built files (in S3). The URLs of these built ones aren't going away. They're no included in any sitemaps or Elasticsearch, but they'll be 200 Ok'ing for a long time.

**Comment by chrisdavidmills** [comment]
@peterbe Ah. We thought it'd just be nice to clear up some of the archived stuff that is really no longer needed. Is it going to be a colossal pain to rebuild archived content? Should we just not bother to touch it where possible?

**Comment by peterbe** [comment]
>  Is it going to be a colossal pain to rebuild archived content?

Not at all. After all, it's good to do that every now and then so the archived content gets the latest design. You just press a button and it's like a regular Prod build but takes a couple of minutes longer.

**Comment by chrisdavidmills** [comment]
> > Is it going to be a colossal pain to rebuild archived content?
> 
> Not at all. After all, it's good to do that every now and then so the archived content gets the latest design. You just press a button and it's like a regular Prod build but takes a couple of minutes longer.

OK, cool. I wonder if we could do something like rebuild the archive content at the end of the week, but only in weeks where some changes have actually been made to `archived-content`? It isn't a huge priority, but also we don't want deleted content links to hang around forever...

**Comment by peterbe** [comment]
Archived content is sticky. It doesn't get automatically removed from S3 when we remove it from `git`.

**Pull request merged**
