### PR TITLE
Archiving HTML - Using the Application cache

### PR DESCRIPTION
**Pull request by SphinxKnight**
After reviewing this page for a French PR, I thought it would be best for anyone's time to move this to the archive.
This is my first PR for archiving content under Yari, let me know if anything else is needed.

See "companion" PRs:
https://github.com/mdn/content/pull/4016
https://github.com/mdn/translated-content/pull/477

### CODE REVIEW

**Comment by peterbe** [comment]
Something must have gone wrong. There's supposed to be 2 files for every page. One `index.html` and one `raw.html`. 
Makes me wonder, do we even have an archiving tool CLI?

**Comment by peterbe** [comment]
Lazy me just checked. We don't have a CLI tool to archive things. We only have a CLI tool to UNarchive things. 

But the archived-content isn't meant to be a "retirement home" really. We created this repo just to have someplace to put the documents, from the Wiki migration, that really don't deserve to be built more than once. Like old things like `Archive/B2G_OS/API`. 

You could have just left it to be deleted from mdn/content and mdn/translated-content. And if someone has an old bookmark pointing to `/$locale/docs/Web/HTML/Using_the_application_cache` we could just add a redirect in the `_redirects.txt` files. 

In fact, later this summer we're going to be abandon and stop publishing the archived content entirely. 

@chrisdavidmills Anything to add to this?

**Comment by SphinxKnight** [comment]
@peterbe I looked for this kind of tool and didn't find one so I've built this PR only by moving files on my filesystem.
That being written, I don't have anything against having this content purely and simply deleted so this PR could be closed as is if necessary :)

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Anything to add to this?

No, not really. Maybe just that this repo is not currently acting as a "retirement home", but I think that would be the idea eventually.

**Comment by SphinxKnight** [comment]
ok, let's close this :)

**Pull request closed without merging**
