### PR TITLE
Remove old documentations

### PR DESCRIPTION
**Pull request by sylvestre**
More details:
https://docs.google.com/spreadsheets/d/1w5WIy_X4vbIWrxH4pC8geqWKgpinj31I9ePwvBcZ9vQ/edit?ts=5f2c0daf#gid=1599531737

### CODE REVIEW

**Comment by sylvestre** [comment]
Done with:
```
L="https://developer.mozilla.org/en-US/docs/Mozilla/Accessibility/Embedding_API_for_Accessibility                                                             
https://developer.mozilla.org/en-US/docs/Mozilla/Accessibility/Gecko_info_for_Windows_accessibility_vendors
"

for f in $L; do P=$(echo $f|rev|cut -d/ -f-1|rev|tr '[:upper:]' '[:lower:]'); git rm -rf $(fd -i $P); git commit -m "Remove $f"; done    
```
But handle with care as the page name might be quite generic

**Review by chrisdavidmills — APPROVED** [review]
I see nothing wrong with the content removed by this PR.

@escattone could someone on your side have a look at this to make sure it is removed in a way that retains platform integrity?

**Comment by peterbe** [comment]
One thing we'll need to do, once this here is finished and deployed, is to re-generate the `archived.txt` file over in Yari:
https://github.com/mdn/yari/blob/2e4323b6276452ea70c220911b0e7aecfd75c5e7/content/archived.txt#L1-L4

**Comment by peterbe** [comment]
If it's helpful, we can do external redirects for these URLs. E.g. adding things to https://github.com/mdn/archived-content/blob/main/files/en-us/_redirects.txt like:
```
/en-US/docs/Mozilla/Gecko[TAB]https://wiki.mozilla.org/Gecko:Home_Page
```

**Comment by sylvestre** [comment]
All but one page have been deleted. So, no need except for 
https://developer.mozilla.org/en-US/docs/Mozilla/HTTP_cache
which should redirect to:
https://firefox-source-docs.mozilla.org/networking/cache2/doc.html

**Comment by sylvestre** [comment]
We are going to do something else.

**Pull request closed without merging**
