### PR TITLE
Delete and redirect internal tree docs (en-US/ja/zh-CN)

### PR DESCRIPTION
**Pull request by SphinxKnight**
I know this repo is not intended to be "active" but this PR originates from a request of @sylvestre regarding Fx contributors who stumble upon the MDN archived docs instead of the in-tree doc.

I was not able to leverage "yarn content" commands for this "delete archived content then redirect" but mimicked what I think was right regarding history and redirects.

I also changed locales where this doc existed.

### CODE REVIEW

**Review by peterbe — APPROVED** [review]
Truth is, we might never render this. 

None of those redirects will kick in unless we make a complete build of all archived-content. 
But if it's important to Sylvestre we can.

**Comment by sylvestre** [comment]
it was mostly important to @padenot :)
I was the messenger

**Comment by sylvestre** [comment]
Many thanks @SphinxKnight btw :)

**Comment by padenot** [comment]
It might be worth it after we migrate more gecko-specific docs to firefox-source-docs, which is currently happening. The SEO of MDN is extremely strong.

**Pull request merged**
